### ISSUE TITLE
Is client code generation possible?

### ISSUE THREAD

**Issue by JunkMyFunk** [bigcommerce/api-specs#378]
Using [openapi-generator ](https://github.com/OpenAPITools/openapi-generator) (with `--skip-validation`) I was able to compile a Python client from these specs for the Catalog V3 API. However it's not usable - every request I try comes back with one error or another, simple operations like getting the catalog summary or a single product fail because of a mismatch between the specs and the actual responses.

Is the intention of this project to enable client code generation or is it simply for the generation of the online documentation? Given that the "official" Python API client is pretty much abandoned and doesn't work with any V3 endpoints, it would be ideal to use this if possible. If we submit issues for the errors we encounter with generated code, will they be addressed?

**Comment by joshdifabio** [comment]
We've been doing so at Space 48 using [openapi-typescript](https://github.com/drwpow/openapi-typescript). The big challenge is that BC's specs contain _a lot_ of mistakes.

See https://github.com/Space48/bigcommerce-api-js

**Comment by JunkMyFunk** [comment]
It would be great if BigCommerce would engage with developers providing feedback and PRs for this. Having complete and accurate OpenAPI specs would [help](https://github.com/bigcommerce/api-specs/issues/397) a [lot](https://github.com/bigcommerce/bigcommerce-api-python/issues/56) of related [issues](https://github.com/bigcommerce/bigcommerce-api-php/issues/261)

**Comment by uwikaiddi** [comment]
Hi @JunkMyFunk, thanks for your patience here! 

My team is in the process of bringing all of our API specs files up-to-date. Since we're a small team and have quite a few APIs, this will take some time.

Our team usually uses this repo with the single purpose of housing our spec files. We have not been checking it regularly for external issues and/or PRs. We usually receive feedback requests via the Docs Feedback buttons located in the bottom-right of each of our API reference pages on our Dev Center.

Now that we're aware of engagement via this repo, we'd be happy to receive any feedback you have via this repo or our Docs Feedback button. 

Thanks again!
