### ISSUE TITLE
Fixing bugs in the specs

### ISSUE THREAD

**Issue by joshdifabio** [bigcommerce/api-specs#397]
In order to improve our productivity at Space 48 we've been using [openapi-typescript](https://github.com/drwpow/openapi-typescript) to generate TypeScript typings for the BigCommerce API endpoints using the specs in this repo.

The major challenge we are facing is that there are a lot of mistakes in your API specs. Specifically, there are fields in the schemas which have the wrong name, wrong type, or are missing altogether.

We are keen to raise PR's on this repo as we find and fix these bugs, but in the past our PR's have been closed without comment or warning[[1]](https://github.com/bigcommerce/api-specs/pull/305)[[2]](https://github.com/bigcommerce/api-specs/pull/306). This poses a significant challenge to us, as we have to maintain a fork of these API specs with our fixes applied, and then continually rebase our fixes onto the changes being made in this repo. This isn't viable as the number of fixes we make increases.

Are BC willing to accept PR's to fix bugs in these specs? Why were our previous PR's closed without comment -- is there something we need to do differently?

BC are currently [suppressing a lot of Spectral errors](https://github.com/bigcommerce/api-specs/blob/master/.spectral.yaml#L6-L10000) which highlight inconsistencies between schemas and example payloads. Is there a goal to eliminate these inconsistencies or is doing so considered out of reach?

**Comment by uwikaiddi** [comment]
Hi @joshdifabio!

I appreciate your patience here. 

My team is in the process of bringing all of our API specs files up-to-date. Since we're a small team and have quite a few APIs, this will take some time.

Our team usually uses this repo with the single purpose of housing our spec files. We have not been checking it regularly for external issues and/or PRs. We usually receive feedback requests via the Docs Feedback buttons located in the bottom-right of each of our API reference pages on our Dev Center.

Now that we're aware of engagement via this repo, we'd be happy to receive any feedback you have via this repo or our Docs Feedback button.

Thanks again!
